---
- name: Crear namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace }}"

- name: Desplegar aplicacion
  kubernetes.core.k8s:
    state: present
    namespace: "{{ app_namespace }}"
    definition: "{{ lookup('template', 'roles/aks/templates/deployment.yml.j2') }}"
